// This file is automatically generated. Do not edit it directly.
"use client";

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Next.js에서는 process.env를 사용하고, 클라이언트에서 접근하려면 NEXT_PUBLIC_ 접두사가 필요합니다
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';

// 환경 변수가 설정되지 않은 경우 경고
if (typeof window !== 'undefined' && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  console.warn(
    '⚠️ Supabase 환경 변수가 설정되지 않았습니다.',
    '\n.env.local 파일에 다음을 추가하세요:',
    '\nNEXT_PUBLIC_SUPABASE_URL=your-project-url',
    '\nNEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=your-anon-key'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 환경 변수가 없으면 클라이언트를 생성하지 않음 (에러를 명확히 하기 위해)
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Supabase 환경 변수가 설정되지 않았습니다!");
  console.error("SUPABASE_URL:", SUPABASE_URL || "(없음)");
  console.error("SUPABASE_PUBLISHABLE_KEY:", SUPABASE_PUBLISHABLE_KEY ? "***" + SUPABASE_PUBLISHABLE_KEY.slice(-4) : "(없음)");
}

// 빈 문자열로 클라이언트를 생성하면 에러가 발생할 수 있으므로, 더미 값으로 초기화
// 하지만 실제로는 환경 변수가 없으면 사용하지 않아야 함
const safeUrl = SUPABASE_URL || 'https://placeholder.supabase.co';
const safeKey = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

export const supabase = createClient<Database>(safeUrl, safeKey, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// 클라이언트 초기화 확인 (개발 환경에서만)
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
  if (safeUrl === SUPABASE_URL && safeKey === SUPABASE_PUBLISHABLE_KEY) {
    console.log("✅ Supabase 클라이언트 초기화 완료");
  } else {
    console.warn("⚠️ Supabase 클라이언트가 Placeholder 값으로 초기화되었습니다.");
  }
}