// This file is automatically generated. Do not edit it directly.
"use client";

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Next.js에서는 process.env를 사용하고, 클라이언트에서 접근하려면 NEXT_PUBLIC_ 접두사가 필요합니다
// 빌드 타임에 환경 변수가 번들에 포함되므로, 런타임에 확인 가능
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';

// 디버깅: 환경 변수 확인 (개발 환경에서만)
if (typeof window !== 'undefined') {
  console.log('🔍 환경 변수 확인:', {
    hasUrl: !!SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    urlLength: SUPABASE_URL.length,
    keyLength: SUPABASE_PUBLISHABLE_KEY.length,
    urlPreview: SUPABASE_URL ? `${SUPABASE_URL.substring(0, 20)}...` : '(없음)',
    keyPreview: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 10)}...` : '(없음)',
  });
}

// 환경 변수가 설정되지 않은 경우 경고
if (typeof window !== 'undefined' && (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY)) {
  console.warn(
    '⚠️ Supabase 환경 변수가 설정되지 않았습니다.',
    '\nVercel 프로젝트 설정에서 다음 환경 변수를 추가하세요:',
    '\nNEXT_PUBLIC_SUPABASE_URL=your-project-url',
    '\nNEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=your-anon-key',
    '\n\n⚠️ 중요: 환경 변수를 추가한 후 반드시 "Redeploy"를 해야 합니다!'
  );
}

// 환경 변수가 없으면 에러를 발생시키지 않고, 명확한 메시지 표시
let supabaseClient: ReturnType<typeof createClient<Database>>;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("❌ Supabase 환경 변수가 설정되지 않았습니다!");
  console.error("Vercel 프로젝트 설정에서 다음 환경 변수를 추가하세요:");
  console.error("  - NEXT_PUBLIC_SUPABASE_URL");
  console.error("  - NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY");
  
  // 더미 클라이언트를 생성하되, 실제 사용 시 에러를 명확히 표시
  const dummyUrl = 'https://placeholder.supabase.co';
  const dummyKey = 'placeholder-key';
  
  supabaseClient = createClient<Database>(dummyUrl, dummyKey, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  
  // 환경 변수가 없을 때는 모든 요청을 차단
  const originalFrom = supabaseClient.from.bind(supabaseClient);
  supabaseClient.from = function(table: any) {
    console.error(`❌ Supabase 환경 변수가 설정되지 않아 "${table}" 테이블에 접근할 수 없습니다.`);
    throw new Error('Supabase 환경 변수가 설정되지 않았습니다. Vercel 프로젝트 설정에서 환경 변수를 추가하세요.');
  } as any;
  
  // auth 메서드도 차단
  const originalAuth = supabaseClient.auth;
  supabaseClient.auth = {
    ...originalAuth,
    signInWithPassword: async () => {
      throw new Error('Supabase 환경 변수가 설정되지 않았습니다. Vercel 프로젝트 설정에서 환경 변수를 추가하세요.');
    },
    signUp: async () => {
      throw new Error('Supabase 환경 변수가 설정되지 않았습니다. Vercel 프로젝트 설정에서 환경 변수를 추가하세요.');
    },
    signOut: async () => {
      throw new Error('Supabase 환경 변수가 설정되지 않았습니다. Vercel 프로젝트 설정에서 환경 변수를 추가하세요.');
    },
    getSession: async () => {
      return { data: { session: null }, error: null };
    },
    getUser: async () => {
      return { data: { user: null }, error: null };
    },
    onAuthStateChange: () => {
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
  } as any;
} else {
  // 환경 변수가 정상적으로 설정된 경우
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  
  // 클라이언트 초기화 확인 (개발 환경에서만)
  if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
    console.log("✅ Supabase 클라이언트 초기화 완료");
  }
}

export const supabase = supabaseClient;
